name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - uses: actions/setup-java@v4.1.0
      with:
        java-version: 17
        distribution: temurin
    - run: sbt test
